server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/ieltsprep
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: //your gmail
    password: //password which is given from account security
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com