server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/ieltsprep
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show_sql: true